{
    'name': 'Pazaryeri Müşteri Soruları',
    'version': '19.0.1.0.0',
    'summary': 'Tüm pazaryerlerinden müşteri sorularını tek panelde yönetin',
    'description': 'Trendyol, Hepsiburada, N11, Pazarama, PTTAVM, Shopify pazaryerlerinden gelen müşteri sorularını tek bir Odoo panelinde toplayın ve doğrudan cevaplayın.',
    'author': 'Uğurlar',
    'category': 'Sales',
    'depends': ['mail', 'product', 'trendyol_integration'],
    'data': [
        'security/ir.model.access.csv',
        'data/default_config.xml',
        'data/ir_cron.xml',
        'views/marketplace_question_views.xml',
        'views/marketplace_answer_views.xml',
        'views/marketplace_template_views.xml',
        'views/dashboard_views.xml',
        'views/trendyol_store_views.xml',
        'views/res_config_settings_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'icon': '/pazaryeri_question/static/description/icon.png',
}
